chore: Updating name, description and name of token

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -1,8 +1,8 @@
-name: Bootstrap a new account in access-control repo
-description: "Sets up a new AWS account and basic roles inside the access control repo"
+name: Pipelines Preflight Checks
+description: "Perform preflight checks before running the pipeline"
 inputs:
-  GRUNTWORK_CODE_ACCESS_TOKEN:
-    description: "The GRUNTWORK_CODE_ACCESS_TOKEN secret"
+  PIPELINES_READ_TOKEN:
+    description: "The PIPELINES_READ_TOKEN secret"
     required: true
 
 runs:
@@ -18,9 +18,9 @@ runs:
     - name: Ensure CI User Variables are populated
       shell: bash
       env:
-        GRUNTWORK_CODE_ACCESS_TOKEN: ${{ inputs.GRUNTWORK_CODE_ACCESS_TOKEN }}
+        PIPELINES_READ_TOKEN: ${{ inputs.PIPELINES_READ_TOKEN }}
       run: |
-        if [[ -z "$GRUNTWORK_CODE_ACCESS_TOKEN" ]]; then echo "Missing GRUNTWORK_CODE_ACCESS_TOKEN"; exit 1; fi
+        if [[ -z "$PIPELINES_READ_TOKEN" ]]; then echo "Missing PIPELINES_READ_TOKEN"; exit 1; fi
     # See https://stackoverflow.com/a/76151412
     - uses: actions/checkout@v4
       # Only run if this is a pull request and the target branch is main
